#mv and cp using rsyng with progress
alias rcp='rsync -aP'
alias rmv='rsync -aP --remove-source-files'

alias vi='nvim'
alias serv='sudo python -m http.server'
alias rpac='sudo rm /var/lib/pacman/db.lck'
alias l='lsd --group-dirs first --date relative -A'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias updt='sudo pacman -Syu'
alias rem='sudo pacman -R'
alias ex='chmod +x'
alias ctl='sudo systemctl'
alias top=bpytop
alias clip='xargs echo -n | xclip -selection clipboard'
alias msgbox='kdialog --msgbox '
alias c=cat
alias cc=ccat
alias grep='rg -i'
alias m=math
alias e='echo'
alias srm="sudo rm -rf "
alias edit='subl'
alias q=fuck
alias fz='z `z| fzf`'
alias lf='fd -d 1 -a -H' # Show full path of files in directory.
alias udb='sudo updatedb'
alias send_to_phone='kdeconnect-cli -d $(kdeconnect-cli -a --id-only) --ping-msg '
alias comp='compdef _gnu_generic ' # Generate completions for command
alias vim='nvim'

alias -g W='|wc -l'
alias -g S='|sed'
alias -g C='|tee >( clip )'
alias -g J='|jq'
alias -g GV='|rg -v'
alias -g A='|awk'
alias -g A1="|awk '{print \$1}'"
alias -g A2="|awk '{print \$2}'"
alias -g A3="|awk '{print \$3}'"
alias -g A4="|awk '{print \$4}'"
alias -g A5="|awk '{print \$5}'"
alias -g A.1="|awk -F. '{print \$1}'"
alias -g A.2="|awk -F. '{print \$2}'"
alias -g A.3="|awk -F. '{print \$3}'"
alias -g A.4="|awk -F. '{print \$4}'"
alias -g A.5="|awk -F. '{print \$5}'"
alias -g A,1="|awk -F, '{print \$1}'"
alias -g A,2="|awk -F, '{print \$2}'"
alias -g A,3="|awk -F, '{print \$3}'"
alias -g A,4="|awk -F, '{print \$4}'"
alias -g A,5="|awk -F, '{print \$5}'"